#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/07748bd3c63b9a5cad29fe7ca01d2112d369c952703a483fb95f34ecd715c0a9/contract';
import endContract from '../../snapshots/07748bd3c63b9a5cad29fe7ca01d2112d369c952703a483fb95f34ecd715c0a9/contract.json' with { type: 'json' };
import type { Contract as Start } from '../../snapshots/651134f9ccfda014c4a27d235488e56b4640ad20fbf307fe0acaa0b8e39566de/contract';
import startContract from '../../snapshots/651134f9ccfda014c4a27d235488e56b4640ad20fbf307fe0acaa0b8e39566de/contract.json' with { type: 'json' };
import { Migration, MigrationCLI } from '@prisma/orm-postgres/migration';

export default class M extends Migration<Start, End> {
  override readonly startContractJson = startContract;
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.alterColumnType({
        schema: 'public',
        table: 'announcements',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'announcements',
        column: 'endAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"endAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'announcements',
        column: 'startAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"startAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'announcements',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_add_sign_tasks',
        column: 'created_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"created_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_add_sign_tasks',
        column: 'updated_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updated_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_flow_number_counters',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_flow_versions',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_flows',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_flows',
        column: 'deletedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"deletedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_flows',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_instance_attachments',
        column: 'created_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"created_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_instances',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_instances',
        column: 'finishedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"finishedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_instances',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_records',
        column: 'created_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"created_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_records',
        column: 'updated_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updated_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_resource_snapshots',
        column: 'created_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"created_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_resource_snapshots',
        column: 'updated_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updated_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_return_back_records',
        column: 'created_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"created_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_return_back_records',
        column: 'updated_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updated_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_tasks',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_tasks',
        column: 'handledAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"handledAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_tasks',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_webhook_deliveries',
        column: 'created_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"created_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_webhook_deliveries',
        column: 'finished_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"finished_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_webhook_deliveries',
        column: 'started_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"started_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'approval_webhook_deliveries',
        column: 'updated_at',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updated_at" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'attachments',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'bidding_infos',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'bidding_infos',
        column: 'deadline',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"deadline" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'bidding_infos',
        column: 'publishedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"publishedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'bidding_keyword_subs',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'bidding_sources',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'bidding_sources',
        column: 'lastFetchAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"lastFetchAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'bidding_sources',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'departments',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'departments',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_ai_model_routes',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_ai_model_routes',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_ai_models',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_ai_models',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_global_task_executions',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_global_task_executions',
        column: 'finishedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"finishedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_global_task_executions',
        column: 'startedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"startedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_global_task_executions',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_global_tasks',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_global_tasks',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_integrations',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_integrations',
        column: 'lastSyncedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"lastSyncedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_integrations',
        column: 'lastTestedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"lastTestedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_integrations',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_mail_settings',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_mail_settings',
        column: 'lastTestedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"lastTestedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_mail_settings',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_term_categories',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_term_categories',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_term_discoveries',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_term_discoveries',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_terms',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_terms',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_ui_settings',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'enterprise_ui_settings',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'export_tasks',
        column: 'completedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"completedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'export_tasks',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'export_tasks',
        column: 'expiresAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"expiresAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'export_tasks',
        column: 'startedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"startedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_department_mappings',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_department_mappings',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_identities',
        column: 'boundAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"boundAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_identities',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_identities',
        column: 'lastLoginAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"lastLoginAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_identities',
        column: 'revokedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"revokedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_identities',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_oauth_states',
        column: 'consumedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"consumedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_oauth_states',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_oauth_states',
        column: 'expiresAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"expiresAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_user_mappings',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'external_user_mappings',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_plan_comment',
        column: 'create_time',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"create_time" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_plan_comment',
        column: 'update_time',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"update_time" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_plans',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_plans',
        column: 'dueNotifiedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"dueNotifiedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_plans',
        column: 'estimatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"estimatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_plans',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_record_comment',
        column: 'create_time',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"create_time" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_record_comment',
        column: 'update_time',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"update_time" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_records',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_records',
        column: 'followedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"followedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'follow_up_records',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'login_logs',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'message_deliveries',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'message_deliveries',
        column: 'nextAttemptAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"nextAttemptAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'message_deliveries',
        column: 'sentAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"sentAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'message_deliveries',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'message_task_settings',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'message_task_settings',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'notifications',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'notifications',
        column: 'readAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"readAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'operation_log_settings',
        column: 'lastCleanupAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"lastCleanupAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'operation_log_settings',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'operation_logs',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_batches',
        column: 'applyStartedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"applyStartedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_batches',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_batches',
        column: 'fetchStartedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"fetchStartedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_batches',
        column: 'finishedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"finishedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_batches',
        column: 'previewedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"previewedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_batches',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_items',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'organization_sync_items',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'plans',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'plans',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'roles',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'roles',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'subscriptions',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'subscriptions',
        column: 'currentPeriodEnd',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"currentPeriodEnd" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'subscriptions',
        column: 'currentPeriodStart',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"currentPeriodStart" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'subscriptions',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'tenants',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'tenants',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'user_key',
        column: 'create_time',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"create_time" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'user_key',
        column: 'expire_time',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"expire_time" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'user_roles',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'user_roles',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'users',
        column: 'createdAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"createdAt" AT TIME ZONE \'UTC\'',
        },
      }),
      this.alterColumnType({
        schema: 'public',
        table: 'users',
        column: 'updatedAt',
        options: {
          qualifiedTargetType: 'timestamptz(3)',
          formatTypeExpected: 'timestamp(3) with time zone',
          rawTargetTypeForLabel: 'timestamptz(3)',
          using: '"updatedAt" AT TIME ZONE \'UTC\'',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
