/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalActionAttachments: typeof import('./../components/ApprovalActionAttachments.vue')['default']
    MobileContactListPane: typeof import('./../components/customer/MobileContactListPane.vue')['default']
    MobileCustomerListPane: typeof import('./../components/customer/MobileCustomerListPane.vue')['default']
    MobileCustomerOpenSeaPane: typeof import('./../components/customer/MobileCustomerOpenSeaPane.vue')['default']
    MobileDynamicForm: typeof import('./../components/MobileDynamicForm.vue')['default']
    MobileFollowUpPlanList: typeof import('./../components/MobileFollowUpPlanList.vue')['default']
    MobileFollowUpSheet: typeof import('./../components/MobileFollowUpSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
