import type { FieldConfig, FieldOption, FieldType } from '@micromatrix/shared'

export interface SystemFieldTemplate {
  key: string
  label: string
  type: FieldType
  required?: boolean
  system?: boolean
  hidden?: boolean
  options?: FieldOption[]
  config?: FieldConfig
  span?: number
  showInList?: boolean
  listWidth?: number
  sort: number
}

const INDUSTRY_OPTIONS: FieldOption[] = [
  { label: '软件与信息服务', value: '软件与信息服务' },
  { label: '互联网', value: '互联网' },
  { label: '装备制造', value: '装备制造' },
  { label: '电子商务', value: '电子商务' },
  { label: '进出口贸易', value: '进出口贸易' },
  { label: '金融', value: '金融' },
  { label: '教育', value: '教育' },
  { label: '医疗健康', value: '医疗健康' },
  { label: '其他', value: '其他' },
]

/**
 * 各业务对象的系统字段模板（首次访问时初始化到租户）。
 * key 与业务表列名一一对应；系统字段不可删除、key/type 不可修改。
 */
const LEAD_SOURCE_OPTIONS: FieldOption[] = [
  { label: '官网表单', value: '官网表单' },
  { label: '电话咨询', value: '电话咨询' },
  { label: '展会活动', value: '展会活动' },
  { label: '朋友介绍', value: '朋友介绍' },
  { label: '标讯', value: '标讯' },
  { label: '广告投放', value: '广告投放' },
  { label: '其他', value: '其他' },
]

const LEAD_LEVEL_OPTIONS: FieldOption[] = [
  { label: '高意向', value: 'A' },
  { label: '中意向', value: 'B' },
  { label: '低意向', value: 'C' },
]

export const MODULE_SYSTEM_FIELDS: Record<string, SystemFieldTemplate[]> = {
  lead: [
    {
      key: 'name',
      label: '线索名称',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    { key: 'contact', label: '联系人', type: 'text', span: 12, listWidth: 110, sort: 1 },
    { key: 'phone', label: '电话', type: 'phone', span: 12, listWidth: 140, sort: 2 },
    {
      key: 'cf_source',
      label: '线索来源',
      type: 'select',
      system: false,
      options: LEAD_SOURCE_OPTIONS,
      span: 12,
      listWidth: 110,
      sort: 3,
    },
    {
      key: 'cf_level',
      label: '意向等级',
      type: 'select',
      system: false,
      options: LEAD_LEVEL_OPTIONS,
      span: 12,
      listWidth: 100,
      sort: 4,
    },
    { key: 'owner', label: '负责人', type: 'member', span: 12, listWidth: 100, sort: 5 },
  ],
  opportunity: [
    {
      key: 'name',
      label: '商机名称',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    { key: 'customerId', label: '客户名称', type: 'text', span: 12, listWidth: 160, sort: 1 },
    { key: 'amount', label: '商机金额', type: 'currency', span: 12, listWidth: 130, sort: 2 },
    { key: 'possible', label: '可能性', type: 'number', span: 12, listWidth: 100, sort: 3 },
    {
      key: 'expectedEndTime',
      label: '结束时间',
      type: 'date',
      span: 12,
      listWidth: 130,
      sort: 4,
    },
    { key: 'products', label: '意向产品', type: 'multiselect', span: 12, listWidth: 160, sort: 5 },
    { key: 'contactId', label: '联系人', type: 'text', span: 12, listWidth: 120, sort: 6 },
    { key: 'owner', label: '负责人', type: 'member', required: true, span: 12, listWidth: 100, sort: 7 },
  ],
  customer: [
    {
      key: 'name',
      label: '客户名称',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 220,
      sort: 0,
    },
    {
      key: 'cf_industry',
      label: '所属行业',
      type: 'select',
      system: false,
      options: INDUSTRY_OPTIONS,
      span: 12,
      listWidth: 140,
      sort: 1,
    },
    {
      key: 'cf_phone',
      label: '联系电话',
      type: 'phone',
      system: false,
      span: 12,
      listWidth: 150,
      sort: 2,
    },
    {
      key: 'cf_email',
      label: '邮箱',
      type: 'email',
      system: false,
      span: 12,
      listWidth: 200,
      sort: 3,
    },
    { key: 'owner', label: '负责人', type: 'member', span: 12, listWidth: 110, sort: 4 },
    {
      key: 'cf_remark',
      label: '备注',
      type: 'textarea',
      system: false,
      span: 24,
      showInList: false,
      sort: 5,
    },
  ],
  contact: [
    { key: 'name', label: '姓名', type: 'text', required: true, span: 12, listWidth: 120, sort: 0 },
    { key: 'customerId', label: '客户', type: 'text', span: 12, listWidth: 180, sort: 1 },
    { key: 'phone', label: '电话', type: 'phone', span: 12, listWidth: 150, sort: 2 },
    { key: 'owner', label: '负责人', type: 'member', span: 12, listWidth: 110, sort: 3 },
    { key: 'enable', label: '状态', type: 'switch', span: 12, listWidth: 90, sort: 4 },
  ],
  product: [
    {
      key: 'name',
      label: '产品名称',
      type: 'text',
      required: true,
      config: { unique: true },
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    { key: 'price', label: '产品价格', type: 'currency', span: 12, listWidth: 120, sort: 1 },
    {
      key: 'status',
      label: '状态',
      type: 'radio',
      required: true,
      options: [
        { label: '上架', value: '1' },
        { label: '下架', value: '2' },
      ],
      config: { defaultValue: '1' },
      span: 12,
      listWidth: 100,
      sort: 2,
    },
    {
      key: 'description',
      label: '描述',
      type: 'textarea',
      system: false,
      span: 24,
      showInList: false,
      sort: 3,
    },
    {
      key: 'productPic',
      label: '产品图片',
      type: 'picture',
      system: false,
      config: { pictureShowType: 'card', uploadLimit: 10, uploadSizeLimit: 20 },
      span: 24,
      showInList: false,
      sort: 4,
    },
  ],
  price: [
    {
      key: 'name',
      label: '价格表名称',
      type: 'text',
      required: true,
      config: { unique: true },
      span: 12,
      listWidth: 220,
      sort: 0,
    },
    {
      key: 'status',
      label: '状态',
      type: 'radio',
      required: true,
      options: [
        { label: '启用', value: '1' },
        { label: '禁用', value: '2' },
      ],
      config: { defaultValue: '1' },
      span: 12,
      listWidth: 100,
      sort: 1,
    },
    {
      key: 'products',
      label: '产品信息',
      type: 'textarea',
      hidden: true,
      showInList: false,
      sort: 2,
    },
    {
      key: 'product',
      label: '产品',
      type: 'text',
      required: true,
      hidden: true,
      showInList: false,
      sort: 3,
    },
    {
      key: 'amount',
      label: '产品定价',
      type: 'currency',
      required: true,
      hidden: true,
      showInList: false,
      sort: 4,
    },
    {
      key: 'priceProductSku',
      label: '产品SKU',
      type: 'text',
      system: false,
      hidden: true,
      showInList: false,
      sort: 5,
    },
    {
      key: 'priceProductTax',
      label: '税点',
      type: 'percent',
      system: false,
      hidden: true,
      showInList: false,
      sort: 6,
    },
    {
      key: 'remark',
      label: '备注',
      type: 'textarea',
      system: false,
      span: 24,
      showInList: false,
      sort: 7,
    },
  ],
  quote: [
    {
      key: 'name',
      label: '报价',
      type: 'text',
      required: true,
      config: { unique: true },
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    {
      key: 'opportunityId',
      label: '商机',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 180,
      sort: 1,
    },
    {
      key: 'contactId',
      label: '联系人',
      type: 'text',
      system: false,
      span: 12,
      showInList: false,
      sort: 2,
    },
    {
      key: 'quotationTime',
      label: '报价日期',
      type: 'date',
      system: false,
      span: 12,
      showInList: false,
      sort: 3,
    },
    {
      key: 'untilTime',
      label: '有效期至',
      type: 'date',
      required: true,
      span: 12,
      listWidth: 120,
      sort: 4,
    },
    {
      key: 'products',
      label: '报价产品',
      type: 'textarea',
      required: true,
      hidden: true,
      showInList: false,
      sort: 5,
    },
    {
      key: 'product',
      label: '产品',
      type: 'text',
      required: true,
      hidden: true,
      showInList: false,
      sort: 6,
    },
    {
      key: 'priceId',
      label: '价格表',
      type: 'text',
      hidden: true,
      showInList: false,
      sort: 7,
    },
    {
      key: 'productAmount',
      label: '产品定价',
      type: 'number',
      hidden: true,
      showInList: false,
      config: { precision: 2 },
      sort: 8,
    },
    {
      key: 'discount',
      label: '折扣',
      type: 'number',
      hidden: true,
      showInList: false,
      config: { precision: 2 },
      sort: 9,
    },
    {
      key: 'tax',
      label: '税点',
      type: 'percent',
      hidden: true,
      showInList: false,
      config: { precision: 2 },
      sort: 10,
    },
    {
      key: 'lineAmount',
      label: '金额',
      type: 'formula',
      hidden: true,
      showInList: false,
      config: { precision: 2 },
      sort: 11,
    },
    {
      key: 'amount',
      label: '累计金额',
      type: 'formula',
      required: true,
      span: 12,
      listWidth: 120,
      config: { precision: 2 },
      sort: 12,
    },
  ],
  contract: [
    {
      key: 'name',
      label: '合同',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    { key: 'customerId', label: '客户名称', type: 'text', required: true, span: 12, listWidth: 180, sort: 1 },
    { key: 'number', label: '合同编号', type: 'text', required: true, span: 12, listWidth: 160, sort: 2 },
    { key: 'products', label: '合同报价信息', type: 'textarea', hidden: true, span: 24, showInList: false, sort: 3 },
    { key: 'product', label: '产品', type: 'text', required: true, hidden: true, span: 12, showInList: false, sort: 4 },
    { key: 'productAmount', label: '产品单价', type: 'currency', required: true, hidden: true, span: 12, showInList: false, sort: 5 },
    { key: 'productNumber', label: '数量', type: 'number', hidden: true, span: 12, showInList: false, sort: 6 },
    { key: 'sumAmount', label: '金额', type: 'formula', hidden: true, span: 12, showInList: false, sort: 7 },
    { key: 'owner', label: '负责人', type: 'member', required: true, span: 12, listWidth: 100, sort: 8 },
    { key: 'startTime', label: '合同开始时间', type: 'date', required: true, span: 12, showInList: false, sort: 9 },
    { key: 'endTime', label: '合同结束时间', type: 'date', required: true, span: 12, listWidth: 110, sort: 10 },
    { key: 'amount', label: '累计金额', type: 'formula', required: true, span: 12, listWidth: 120, sort: 11 },
  ],
  contractPaymentPlan: [
    {
      key: 'name',
      label: '回款计划名称',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    {
      key: 'contractId',
      label: '合同',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 180,
      sort: 1,
    },
    {
      key: 'owner',
      label: '负责人',
      type: 'member',
      required: true,
      span: 12,
      listWidth: 120,
      sort: 2,
    },
    {
      key: 'planAmount',
      label: '计划回款金额',
      type: 'currency',
      required: true,
      config: { precision: 2 },
      span: 12,
      listWidth: 140,
      sort: 3,
    },
    {
      key: 'planEndTime',
      label: '计划回款时间',
      type: 'date',
      required: true,
      span: 12,
      listWidth: 130,
      sort: 4,
    },
  ],
  contractPaymentRecord: [
    {
      key: 'name',
      label: '回款记录名称',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    {
      key: 'no',
      label: '回款编码',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 160,
      sort: 1,
    },
    {
      key: 'contractId',
      label: '合同名称',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 180,
      sort: 2,
    },
    {
      key: 'paymentPlanId',
      label: '回款计划',
      type: 'text',
      span: 12,
      listWidth: 180,
      sort: 3,
    },
    {
      key: 'owner',
      label: '负责人',
      type: 'member',
      required: true,
      span: 12,
      listWidth: 120,
      sort: 4,
    },
    {
      key: 'recordEndTime',
      label: '回款时间',
      type: 'date',
      required: true,
      span: 12,
      listWidth: 130,
      sort: 5,
    },
    {
      key: 'recordAmount',
      label: '回款金额',
      type: 'currency',
      required: true,
      config: { precision: 2 },
      span: 12,
      listWidth: 140,
      sort: 6,
    },
    {
      key: 'contractPaymentRecordBank',
      label: '收款银行',
      type: 'select',
      system: false,
      required: true,
      options: [
        { label: '中国银行', value: '1' },
        { label: '中国农业银行', value: '2' },
        { label: '中国工商银行', value: '3' },
        { label: '中国建设银行', value: '4' },
      ],
      span: 12,
      listWidth: 140,
      sort: 7,
    },
    {
      key: 'contractPaymentRecordBankNo',
      label: '收款银行账号',
      type: 'select',
      system: false,
      required: true,
      options: [
        { label: '银行账号1', value: '1' },
        { label: '银行账号2', value: '2' },
        { label: '银行账号3', value: '3' },
      ],
      span: 12,
      listWidth: 160,
      sort: 8,
    },
  ],
  followPlan: [
    {
      key: 'targetType',
      label: '关联类型',
      type: 'select',
      required: true,
      options: [
        { label: '客户', value: 'customer' },
        { label: '线索', value: 'lead' },
        { label: '商机', value: 'opportunity' },
      ],
      span: 12,
      listWidth: 100,
      sort: 0,
    },
    {
      key: 'targetId',
      label: '关联对象',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 180,
      sort: 1,
    },
    {
      key: 'ownerId',
      label: '负责人',
      type: 'member',
      required: true,
      span: 12,
      listWidth: 110,
      sort: 2,
    },
    { key: 'contactId', label: '联系人', type: 'text', span: 12, listWidth: 120, sort: 3 },
    {
      key: 'estimatedAt',
      label: '计划时间',
      type: 'date',
      span: 12,
      listWidth: 150,
      sort: 4,
    },
    {
      key: 'content',
      label: '预计沟通内容',
      type: 'textarea',
      required: true,
      span: 24,
      listWidth: 220,
      sort: 5,
    },
    { key: 'method', label: '跟进方式', type: 'text', span: 12, listWidth: 110, sort: 6 },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      options: [
        { label: '未开始', value: 'PREPARED' },
        { label: '进行中', value: 'UNDERWAY' },
        { label: '已完成', value: 'COMPLETED' },
        { label: '已取消', value: 'CANCELLED' },
      ],
      span: 12,
      listWidth: 100,
      sort: 7,
    },
  ],
  invoice: [
    {
      key: 'name',
      label: '发票名称',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    {
      key: 'contractId',
      label: '合同',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 180,
      sort: 1,
    },
    {
      key: 'owner',
      label: '负责人',
      type: 'member',
      required: true,
      span: 12,
      listWidth: 120,
      sort: 2,
    },
    {
      key: 'amount',
      label: '开票金额',
      type: 'currency',
      required: true,
      config: { precision: 2 },
      span: 12,
      listWidth: 140,
      sort: 3,
    },
    {
      key: 'invoiceType',
      label: '发票类型',
      type: 'text',
      span: 12,
      listWidth: 140,
      sort: 4,
    },
    {
      key: 'taxRate',
      label: '税率',
      type: 'number',
      config: { precision: 2 },
      span: 12,
      listWidth: 100,
      sort: 5,
    },
    {
      key: 'businessTitleId',
      label: '工商抬头',
      type: 'text',
      span: 12,
      listWidth: 180,
      sort: 6,
    },
  ],
  order: [
    {
      key: 'name',
      label: '订单名称',
      type: 'text',
      required: true,
      config: { unique: true },
      span: 12,
      listWidth: 200,
      sort: 0,
    },
    {
      key: 'number',
      label: '订单编号',
      type: 'text',
      required: true,
      config: { unique: true },
      span: 12,
      listWidth: 160,
      sort: 1,
    },
    {
      key: 'customerId',
      label: '关联客户',
      type: 'text',
      required: true,
      span: 12,
      listWidth: 180,
      sort: 2,
    },
    {
      key: 'contractId',
      label: '关联合同',
      type: 'text',
      span: 12,
      listWidth: 180,
      sort: 3,
    },
    {
      key: 'owner',
      label: '负责人',
      type: 'member',
      required: true,
      span: 12,
      listWidth: 120,
      sort: 4,
    },
    {
      key: 'amount',
      label: '订单金额',
      type: 'formula',
      required: true,
      config: { precision: 2 },
      span: 12,
      listWidth: 140,
      sort: 5,
    },
    {
      key: 'orderProducts',
      label: '产品明细',
      type: 'textarea',
      hidden: true,
      span: 24,
      showInList: false,
      sort: 6,
    },
    {
      key: 'orderProduct',
      label: '产品名称',
      type: 'text',
      hidden: true,
      span: 12,
      showInList: false,
      sort: 7,
    },
    {
      key: 'orderProductPrice',
      label: '产品单价',
      type: 'currency',
      hidden: true,
      span: 12,
      showInList: false,
      sort: 8,
    },
    {
      key: 'orderProductNumber',
      label: '数量',
      type: 'number',
      hidden: true,
      span: 12,
      showInList: false,
      sort: 9,
    },
    {
      key: 'orderProductAmount',
      label: '金额',
      type: 'formula',
      hidden: true,
      span: 12,
      showInList: false,
      sort: 10,
    },
    {
      key: 'orderDeliveryAddress',
      label: '收货地址',
      type: 'text',
      system: false,
      span: 24,
      showInList: false,
      sort: 11,
    },
    {
      key: 'orderConsignee',
      label: '收货人',
      type: 'text',
      system: false,
      span: 12,
      showInList: false,
      sort: 12,
    },
    {
      key: 'orderPhone',
      label: '收货人联系方式',
      type: 'phone',
      system: false,
      span: 12,
      showInList: false,
      sort: 13,
    },
  ],
}
